# coding: utf-8

"""
    Obstacle Detection Result

    This is the REST API endpoint specification for processing the results of the obstacle detection process. For the obstacle detection module see [this repository](https://github.com/karolyartur/obstacle-detection).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fleet_manager_client
from fleet_manager_client.models.header import Header  # noqa: E501
from fleet_manager_client.rest import ApiException


class TestHeader(unittest.TestCase):
    """Header unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHeader(self):
        """Test Header"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fleet_manager_client.models.header.Header()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
