# coding: utf-8

# flake8: noqa
"""
    Obstacle Detection Result

    This is the REST API endpoint specification for processing the results of the obstacle detection process. For the obstacle detection module see [this repository](https://github.com/karolyartur/obstacle-detection).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from fleet_manager_client.models.header import Header
from fleet_manager_client.models.position import Position
from fleet_manager_client.models.result import Result
from fleet_manager_client.models.velocity import Velocity
