# coding: utf-8

"""
    Obstacle Detection Result

    This is the REST API endpoint specification for processing the results of the obstacle detection process. For the obstacle detection module see [this repository](https://github.com/karolyartur/obstacle-detection).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "fleet-manager-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Obstacle Detection Result",
    author_email="",
    url="",
    keywords=["Swagger", "Obstacle Detection Result"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    This is the REST API endpoint specification for processing the results of the obstacle detection process. For the obstacle detection module see [this repository](https://github.com/karolyartur/obstacle-detection).   # noqa: E501
    """
)
